PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'2026_08_16_214432_create_users_table',1);
INSERT INTO migrations VALUES(2,'2026_08_16_214438_create_profiles_table',1);
INSERT INTO migrations VALUES(3,'2026_08_16_214444_create_movies_table',1);
INSERT INTO migrations VALUES(4,'2026_08_16_214448_create_tags_table',1);
INSERT INTO migrations VALUES(5,'2026_08_16_214452_create_movie_tag_table',1);
INSERT INTO migrations VALUES(6,'2026_08_16_222457_create_sessions_table',1);
INSERT INTO migrations VALUES(7,'2026_08_16_230938_create_cache_table',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "display_name" varchar not null, "email" varchar not null, "password" varchar not null, "created_at" datetime, "updated_at" datetime);
INSERT INTO users VALUES(1,'Usuário Demo','demo@cinelist.test','$2y$12$Z8KEcQ6xf9vTuK9U1pMw6OhcaEjBjiq0AqByAT/Q81hlyWLPogb/e','2026-09-23 16:56:30','2026-09-23 16:58:53');
CREATE TABLE IF NOT EXISTS "profiles" ("id" integer primary key autoincrement not null, "user_id" integer not null, "name" varchar not null, "avatar" varchar, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "movies" ("id" varchar not null, "user_id" integer not null, "created_by_name" varchar not null, "title" varchar not null, "director" varchar, "year" integer, "genres" text, "synopsis" text, "poster_url" varchar, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, primary key ("id"));
INSERT INTO movies VALUES('a2d0f097-36f9-40ee-881c-dbc41c43ff79',1,'Elvera Padberg II','Voluptatem ad necessitatibus cupiditate.','Cordia Lesch',2013,'["Aventura"]','Aut odit commodi et omnis et aut. Cumque delectus molestiae repellat omnis perspiciatis. Quia praesentium nobis nobis. Eligendi occaecati nam distinctio.',NULL,'2026-09-23 16:58:53','2026-09-23 16:58:53');
INSERT INTO movies VALUES('a2d0f097-39af-4705-9817-10f4f6438515',1,'Roxane Wisozk Sr.','Aut et doloremque debitis.','Wava Dooley',1985,'["Terror"]','Earum alias quia ut sunt. Incidunt iusto blanditiis laudantium reiciendis laboriosam perspiciatis fugit. Vero est sed id. Numquam sunt repellendus placeat numquam ut enim.',NULL,'2026-09-23 16:58:53','2026-09-23 16:58:53');
INSERT INTO movies VALUES('a2d0f097-3a78-423a-82bd-03ee89ead29d',1,'Leland Ebert','Mollitia debitis magnam.','Isobel Williamson',1987,'["Aventura"]','Libero et nobis provident perferendis amet illum molestias. Enim perferendis cupiditate ullam veritatis sit. Et sint et et officia ut numquam. Ea nisi placeat eos voluptatem rerum sed. Ut cum dicta et eos dolores quia dolorum.',NULL,'2026-09-23 16:58:53','2026-09-23 16:58:53');
INSERT INTO movies VALUES('a2d0f097-3b5c-49e2-a332-8ce61c05130c',1,'Lottie Heller DDS','Eveniet dolorem deleniti quod.','Nestor Jast',2007,'["Com\u00e9dia"]','Nulla rerum impedit esse qui reprehenderit. Voluptas animi ut beatae aut. Occaecati cumque labore necessitatibus ad nulla veniam.',NULL,'2026-09-23 16:58:53','2026-09-23 16:58:53');
INSERT INTO movies VALUES('a2d0f097-3c12-40c7-81e5-d4ff5e179649',1,'Roberto West','Eos placeat harum.','Mr. Jadon Shanahan',2000,'["Com\u00e9dia"]','Molestiae aliquid dolorem iusto et eveniet iusto aliquam ut. Aperiam quia autem est. Et omnis quibusdam iusto velit.',NULL,'2026-09-23 16:58:53','2026-09-23 16:58:53');
CREATE TABLE IF NOT EXISTS "tags" ("id" integer primary key autoincrement not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "movie_tag" ("id" integer primary key autoincrement not null, "movie_id" varchar not null, "tag_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("movie_id") references "movies"("id") on delete cascade, foreign key("tag_id") references "tags"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',7);
INSERT INTO sqlite_sequence VALUES('users',1);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE UNIQUE INDEX "tags_name_unique" on "tags" ("name");
CREATE UNIQUE INDEX "movie_tag_movie_id_tag_id_unique" on "movie_tag" ("movie_id", "tag_id");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
COMMIT;
